### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by anklee** [learnforpractice/pyeos#42]
[ 11%] Linking CXX shared library libmicropython3.so
/usr/bin/ld: CMakeFiles/micropython3.dir/py/nlrx64.c.o: relocation R_X86_64_PC32 against symbol `nlr_push_tail' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
libraries/micropython/CMakeFiles/micropython3.dir/build.make:3070: recipe for target 'libraries/micropython/libmicropython3.so' failed
make[2]: *** [libraries/micropython/libmicropython3.so] Error 1
CMakeFiles/Makefile2:728: recipe for target 'libraries/micropython/CMakeFiles/micropython3.dir/all' failed
make[1]: *** [libraries/micropython/CMakeFiles/micropython3.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by learnforpractice** [comment]
Thanks, @anklee, I’m working on it. It will take more time since I compile it in Docker. Will inform you when it’s ready.

**Comment by learnforpractice** [comment]
Hi, @anklee, you can have a try now. Keeping platform compatibility is hard when you are busy developing. Thanks for your patience. Use the following command to update and compile your source code:

git pull
git submodule update --init —recursive


rm libraries/python/pyconfig.h
rm -rf libraries/python/dist

./eosio_build.sh



Let me know if you have additional problems.

**Comment by anklee** [comment]
EOS.IO has been successfully built. 0:8:36
Thanks
