### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by anklee** [learnforpractice/pyeos#43]
When I start pyeos , found a error"ModuleNotFoundError".
./pyeos/pyeos -i --manual-gen-block --debug --data-dir=data-dir --config-dir=config-dir

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "../../programs/pyeos/contracts/cryptokitties/test.py", line 6, in <module>
    import subprocess
  File "/home/anklee/pyeos/libraries/python/dist/lib/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ModuleNotFoundError: No module named '_posixsubprocess'
please make sure you are running the following command before test
./pyeos/pyeos --manual-gen-block --debug -i
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "../../programs/pyeos/contracts/currency/test.py", line 1, in <module>
    import pickle
  File "/home/anklee/pyeos/libraries/python/dist/lib/python3.6/pickle.py", line 33, in <module>
    from struct import pack, unpack
  File "/home/anklee/pyeos/libraries/python/dist/lib/python3.6/struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'

**Comment by learnforpractice** [comment]
Fixed, sorry for the inconvenience.

**Comment by anklee** [comment]
The same error.
ModuleNotFoundError: No module named '_posixsubprocess'
ModuleNotFoundError: No module named '_struct'

**Comment by learnforpractice** [comment]
Well, please check CMakeLists.txt in programs/pyeos, make sure it’s update to date, pay attention to the red words, they should be exists.


if( APPLE )
target_link_libraries( pyeos appbase account_history_api_plugin account_history_plugin chain_api_plugin 
    producer_plugin chain_plugin net_plugin http_plugin fc ${CMAKE_DL_LIBS} ${PLATFORM_SPECIFIC_LIBS} 
    wallet_plugin wallet_api_plugin
    chainbase eos_utilities fc
    python3 eosio_chain intl )
else( APPLE )
target_link_libraries( pyeos appbase account_history_api_plugin account_history_plugin chain_api_plugin 
    producer_plugin chain_plugin net_plugin http_plugin fc ${CMAKE_DL_LIBS} ${PLATFORM_SPECIFIC_LIBS} 
    wallet_plugin wallet_api_plugin
    chainbase eos_utilities fc
    python3 eosio_chain util -Xlinker -export-dynamic)

endif( APPLE )

**Comment by anklee** [comment]
~/pyeos/programs/pyeos$ nano CMakeLists.tx

if( APPLE )
target_link_libraries( pyeos appbase account_history_api_plugin account_history_plugin chain_api_plugin
 producer_plugin chain_plugin net_plugin http_plugin fc ${CMAKE_DL_LIBS} ${PLATFORM_SPECIFIC_LIBS}
    wallet_plugin wallet_api_plugin
    chainbase eos_utilities fc
    python3 eosio_chain intl )
else( APPLE )
target_link_libraries( pyeos appbase account_history_api_plugin account_history_plugin chain_api_plugin
 producer_plugin chain_plugin net_plugin http_plugin fc ${CMAKE_DL_LIBS} ${PLATFORM_SPECIFIC_LIBS}
    wallet_plugin wallet_api_plugin
    chainbase eos_utilities fc
    python3 eosio_chain util -Xlinker -export-dynamic)

endif( APPLE )

**Comment by learnforpractice** [comment]
Weird, anyone encounter the some problem? Work like a charm here.

**Comment by anklee** [comment]
anklee@ubuntu:~/pyeos/build/programs$ ./pyeos/pyeos -i --manual-gen-block --debug --data-dir=data-dir --config-dir=config-dir427780ms thread-0   mpeoslib.cpp:79               get_mpapi            ] ../libraries/micropython/libmicropython1.so, 62268064
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'readline'
427900ms thread-1   chain_plugin.cpp:99           plugin_initialize    ] initializing chain plugin
427900ms thread-1   wallet_plugin.cpp:41          plugin_initialize    ] initializing wallet plugin
427900ms thread-1   http_plugin.cpp:141           plugin_initialize    ] host: 127.0.0.1 port: 8888
427901ms thread-1   http_plugin.cpp:144           plugin_initialize    ] configured http to listen on 127.0.0.1:8888
427901ms thread-1   net_plugin.cpp:2628           plugin_initialize    ] Initialize net plugin
427901ms thread-1   net_plugin.cpp:2644           plugin_initialize    ] Setting net_plugin logging level to info
427901ms thread-1   net_plugin.cpp:2669           plugin_initialize    ] host: 0.0.0.0 port: 9876
427902ms thread-1   net_plugin.cpp:2745           plugin_initialize    ] my node_id is ec28a7fb09313fa4679957ea6f22fceae0febfea7aa6404f3d3999cd13dab47b
427902ms thread-1   py_plugin.cpp:97              plugin_startup       ] py_plugin::plugin_startup
427903ms thread-1   block_log.cpp:120             open                 ] Log is nonempty
427903ms thread-1   block_log.cpp:128             open                 ] Index is nonempty
427914ms thread-1   chain_plugin.cpp:208          plugin_startup       ] starting chain in read/write mode
427914ms thread-1   chain_plugin.cpp:213          plugin_startup       ] Blockchain started; head block is #7, genesis timestamp is 2018-03-01T12:00:00.000
427914ms thread-1   producer_plugin.cpp:167       plugin_startup       ] producer plugin:  plugin_startup() begin
427914ms thread-1   producer_plugin.cpp:172       plugin_startup       ] Launching block production for 1 producers.
427914ms thread-1   producer_plugin.cpp:184       plugin_startup       ] producer plugin:  plugin_startup() end
427914ms thread-1   http_plugin.cpp:213           plugin_startup       ] start listening for http requests
427914ms thread-1   wallet_api_plugin.cpp:75      plugin_startup       ] starting wallet_api_plugin
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/create
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/get_public_keys
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/import_key
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/list_keys
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/list_wallets
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/lock
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/lock_all
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/open
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/save
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/set_timeout
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/sign_transaction
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/wallet/unlock
427915ms thread-1   chain_api_plugin.cpp:62       plugin_startup       ] starting chain_api_plugin
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/abi_bin_to_json
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/abi_json_to_bin
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_account
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_block
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_code
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_currency_balance
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_currency_stats
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_info
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_required_keys
427915ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/get_table_rows
427916ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_block
427916ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_transaction
427916ms thread-1   http_plugin.cpp:242           add_handler          ] add api url: /v1/chain/push_transactions
427916ms thread-1   net_plugin.cpp:2757           plugin_startup       ] starting listener, max clients is 25
427985ms thread-0   fork_database.cpp:77          _push_block          ] Number of missed blocks: 40
eosio generated block 91bc2b99... #8 @ 2018-04-14T12:07:07.500 with 0 trxs, lib: 7
427985ms thread-0   producer_plugin.cpp:199       produce_block        ] block_production_loop return: 0
427986ms thread-0   producer_plugin.cpp:199       produce_block        ] block_production_loop return: 3
427987ms thread-0   producer_plugin.cpp:199       produce_block        ] block_production_loop return: 3
427987ms thread-0   producer_plugin.cpp:199       produce_block        ] block_production_loop return: 3
please make sure you are running the following command before test
./pyeos/pyeos --manual-gen-block --debug -i
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "../../programs/pyeos/contracts/cryptokitties/test.py", line 6, in <module>
    import subprocess
  File "/home/anklee/pyeos/libraries/python/dist/lib/python3.6/subprocess.py", line 136, in <module>
    import _posixsubprocess
ModuleNotFoundError: No module named '_posixsubprocess'
please make sure you are running the following command before test
./pyeos/pyeos --manual-gen-block --debug -i
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "../../programs/pyeos/contracts/currency/test.py", line 1, in <module>
    import pickle
  File "/home/anklee/pyeos/libraries/python/dist/lib/python3.6/pickle.py", line 33, in <module>
    from struct import pack, unpack
  File "/home/anklee/pyeos/libraries/python/dist/lib/python3.6/struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'
please make sure you are running the following command before test
./pyeos/pyeos --manual-gen-block --debug -i
please make sure you are running the following command before test
./pyeos/pyeos --manual-gen-block --debug -i
please make sure you are running the following command before test
./pyeos/pyeos --manual-gen-block --debug -i
please make sure you are running the following command before test
./pyeos/pyeos --manual-gen-block --debug -i
428009ms thread-0   main.cpp:194                  interactive_console  ] start interactive python.
>>>

**Comment by anklee** [comment]
ModuleNotFoundError: No module named 'readline'
ModuleNotFoundError: No module named '_posixsubprocess'
ModuleNotFoundError: No module named '_struct'

570121ms thread-0   chain_plugin.cpp:423          push_transaction     ] abi_serializer::to_variant failed!

**Comment by anklee** [comment]
export PYTHONHOME=$HOME/pyeos/libraries/python/dist

**Comment by learnforpractice** [comment]
Yes, sounds like Python is not smart enough on Ubuntu 7
