### ISSUE TITLE
No package 'libffi' found

### ISSUE THREAD

**Issue by sindbad** [learnforpractice/pyeos#45]
mac OS Sierra 10.12.6
./eosio_build.sh
---------------------------------------------

.......

Requirement already up-to-date: pip in ./dist/lib/python3.6/site-packages
Collecting cython
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/dd/1f/fbc379eeb53eedbff12d0623a154902c06ac6a386830cdc30d4ccb874453/Cython-0.28.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (5.2MB)
    100% |████████████████████████████████| 5.2MB 187kB/s
Installing collected packages: cython
Successfully installed cython-0.28.1
Scanning dependencies of target python3
[  4%] Building CXX object libraries/python/CMakeFiles/python3.dir/start.cpp.o
[  4%] Linking CXX static library libpython3.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.a(start.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.a(start.cpp.o) has no symbols
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: warning for library: libpython3.a the table of contents is empty (no object file members in the library define global symbols)
[  4%] Built target python3
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by learnforpractice** [comment]
"(start.cpp.o) has no symbols" was not the cause of errors, please use the following command to compile your source and upload compile.log to github.
```
./eosio_build.sh >compile.log 2>&1
```

**Comment by sindbad** [comment]
[complie.log](https://github.com/learnforpractice/pyeos/files/1907320/complie.log)

**Comment by sindbad** [comment]
I try to install 'libffi' by brew:
➜  pyeos git:(master) ✗ brew install libffi
Updating Homebrew...
Warning: libffi 3.2.1 is already installed and up-to-date
To reinstall 3.2.1, run `brew reinstall libffi`

**Comment by learnforpractice** [comment]
Please try:
brew link libffi

libffi will be removed from building as it's no need by pyeos

**Comment by sindbad** [comment]
➜  pyeos git:(master) ✗ brew link libffi
Warning: libffi is keg-only and must be linked with --force
Note that doing so can interfere with building software.

**Comment by learnforpractice** [comment]
Yes, try：

brew link —force libff

**Comment by sindbad** [comment]
pyeos git:(master) ✗ brew link --force libff
Error: No such keg: /usr/local/Cellar/libff

**Comment by learnforpractice** [comment]
OK, I have submitted a patch to remove libffi from building, please update your source with the following command:

git pull
git submodule update --init --recursive  

Good luck!
