### ISSUE TITLE
Error fetching submodules

### ISSUE THREAD

**Issue by pfgoting** [learnforpractice/pyeos#60]
Hello! I am unble to build pyeos on my system (Ubuntu 14.04) because of this error when fetching [submodules](https://scontent.fmnl10-1.fna.fbcdn.net/v/t1.15752-9/36585211_10209421105004181_7125571728721313792_n.png?_nc_cat=0&oh=61408008ca5fc621d0170c4a89bdfaec&oe=5BDF924E). Do you have any fix maybe?

**Comment by learnforpractice** [comment]
Fixed, thanks.
