### ISSUE TITLE
Error Building

### ISSUE THREAD

**Issue by tjdans1114** [learnforpractice/pyeos#61]
While building pyeos (in mac High Sierra 10.13.2) through eosio_build.sh, below error occured. I can't figure what this error is. 
How can I fix this issue? Thank you.

....

[  8%] linking python3.6.4
Scanning dependencies of target python3
[  8%] Building CXX object libraries/python/CMakeFiles/python3.dir/start.cpp.o
[  8%] Building C object libraries/python/CMakeFiles/python3.dir/dummy.c.o
[  8%] Linking CXX static library libpython3.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.a(dummy.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpython3.a(dummy.c.o) has no symbols
[  8%] Built target python3
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by learnforpractice** [comment]
Can you submit a full log?
