### ISSUE TITLE
build error: libsecp256k1.a: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object

### ISSUE THREAD

**Issue by lisoleg** [learnforpractice/pyeos#62]
[ 26%] Linking CXX shared library libfc.so
/usr/bin/ld: /usr/local/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libsecp256k1.a: 无法添加符号: 错误的值
clang: error: linker command failed with exit code 1 (use -v to see invocation)
libraries/fc/CMakeFiles/fc.dir/build.make:1544: recipe for target 'libraries/fc/libfc.so' failed
make[2]: *** [libraries/fc/libfc.so] Error 1
CMakeFiles/Makefile2:6349: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

	>>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by learnforpractice** [comment]
Thanks for the report, it's been fixed. Please update your code to the last version and try again.

**Comment by lisoleg** [comment]
Sorry, I pull the latest master branch, but the issue still open
