### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dlwogus5038** [learnforpractice/pyeos#63]
I tried to build your Pyeos, and I found these errors

>>>>>>>> ALL dependencies sucessfully found or installed . Installing EOSIO

>>>>>>>> CMAKE_BUILD_TYPE=Release
>>>>>>>> ENABLE_COVERAGE_TESTING=false
>>>>>>>> DOXYGEN=false

-- [cable ] Cable 0.2.9 initialized

clang not found

CMake Error at /home/ubuntu/pyeos/cmake/polly/utilities/polly_fatal_error.cmake:10 (message):
Call Stack (most recent call first):
  /home/ubuntu/pyeos/cmake/polly/compiler/clang.cmake:23 (polly_fatal_error)
  /home/ubuntu/pyeos/cmake/polly/clang-fpic.cmake:19 (include)
  /usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:2 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

[hunter ** INTERNAL **] Configure project failed
[hunter ** INTERNAL **] [Directory:/home/ubuntu/pyeos]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/HunterGate.cmake:83 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:93 (hunter_gate_wiki)
  cmake/HunterGate.cmake:333 (hunter_gate_internal_error)
  cmake/HunterGate.cmake:513 (hunter_gate_download)
  CMakeLists.txt:44 (HunterGate)

-- Configuring incomplete, errors occurred!

    >>>>>>>>>>>>>>>>>>>> CMAKE building EOSIO has exited with the above error. 

I'm using Ubuntu 18.04 / cmake 3.10.2
How can i solve this problem?

**Comment by learnforpractice** [comment]
Sounds like you have to install clang manually.
I'm using Ubuntu 16.04 and I don't have Ubuntu 18.04 installed, so I can't test it on Ubuntu 18.04. Probably the fast solution is downgrade you Ubuntu to 16.04.

**Comment by dlwogus5038** [comment]
I already tried to build it on Ubuntu16.04, and it didn't work for me

**Comment by dlwogus5038** [comment]
Is there any package that I should install before building your pyeos? Yesterday i just installed g++ and git, and then tried to build pyeos

**Comment by dlwogus5038** [comment]
And there is no error when i build EOS

**Comment by dlwogus5038** [comment]
OHHHHHHHHHH I installed clang manually, and it work for me!! thank you :)
