### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dlwogus5038** [learnforpractice/pyeos#65]
[ 28%] making python3.7 

make[3]: warning: -jN forced in submake: disabling jobserver mode.
[ 28%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/sha1.cpp.o
[ 28%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/ripemd160.cpp.o
[ 28%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/sha256.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/sha224.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/sha512.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/dh.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/blowfish.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/elliptic_common.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/elliptic_impl_priv.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/elliptic_secp256k1.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/elliptic_r1.cpp.o
In file included from Objects/stringlib/unicode_format.h:933:0,
                 from Objects/unicodeobject.c:13718:
./inspector/inspector.h:13:10: fatal error: eosiolib_native/vm_api.h: No such file or directory
 #include <eosiolib_native/vm_api.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1623: recipe for target 'Objects/unicodeobject.o' failed
make[3]: *** [Objects/unicodeobject.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/ubuntu/pyeos/libraries/fc/src/crypto/elliptic_r1.cpp:19:22: warning: unused variable 'init'
      [-Wunused-variable]
          static int init = init_openssl();
                     ^
/home/ubuntu/pyeos/libraries/fc/src/crypto/elliptic_r1.cpp:41:22: warning: unused variable 'init'
      [-Wunused-variable]
          static int init = init_openssl();
                     ^
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/rand.cpp.o
2 warnings generated.
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/public_key.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/private_key.cpp.o
externals/python/CMakeFiles/python3.dir/build.make:65: recipe for target '../externals/python/libpython3.7m.so' failed
make[2]: *** [../externals/python/libpython3.7m.so] Error 2
CMakeFiles/Makefile2:796: recipe for target 'externals/python/CMakeFiles/python3.dir/all' failed
make[1]: *** [externals/python/CMakeFiles/python3.dir/all] Error 2
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/signature.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/network/ip.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/network/resolve.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/network/udp_socket.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/network/url.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/network/http/http_client.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/compress/smaz.cpp.o
[ 29%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/compress/zlib.cpp.o
[ 29%] Building C object libraries/fc/CMakeFiles/fc.dir/src/crypto/xxhash.c.o
[ 30%] Linking CXX shared library libfc.so
/usr/bin/ld: /usr/local/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
libraries/fc/CMakeFiles/fc.dir/build.make:1544: recipe for target 'libraries/fc/libfc.so' failed
make[2]: *** [libraries/fc/libfc.so] Error 1
CMakeFiles/Makefile2:5883: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

    >>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by learnforpractice** [comment]
Fixed. Thanks for the report.
