### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by dlwogus5038** [learnforpractice/pyeos#66]
[ 28%] Built target thrift_static
[ 28%] Built target chainbase
[ 28%] Built target eosio_prods_static
Scanning dependencies of target chainbase_test
fatal: No names found, cannot describe anything.
CMake Error at version.cmake:11 (message):
  git describe failed

libraries/appbase/CMakeFiles/appbase_version.dir/build.make:57: recipe for target 'libraries/appbase/CMakeFiles/appbase_version' failed
make[2]: *** [libraries/appbase/CMakeFiles/appbase_version] Error 1
CMakeFiles/Makefile2:5525: recipe for target 'libraries/appbase/CMakeFiles/appbase_version.dir/all' failed
make[1]: *** [libraries/appbase/CMakeFiles/appbase_version.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
Fatal Error: Unable to find package java.lang in classpath or bootclasspath
[ 29%] Linking CXX shared library libfc.so
libraries/vm/vm_java/CMakeFiles/vm_java.dir/build.make:70: recipe for target 'libraries/vm/vm_java/VMMain.class' failed
make[2]: *** [libraries/vm/vm_java/VMMain.class] Error 3
CMakeFiles/Makefile2:4200: recipe for target 'libraries/vm/vm_java/CMakeFiles/vm_java.dir/all' failed
make[1]: *** [libraries/vm/vm_java/CMakeFiles/vm_java.dir/all] Error 2
/usr/bin/ld: /usr/local/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
**clang: error: linker command failed with exit code 1 (use -v to see invocation)**
libraries/fc/CMakeFiles/fc.dir/build.make:1544: recipe for target 'libraries/fc/libfc.so' failed
make[2]: *** [libraries/fc/libfc.so] Error 1
CMakeFiles/Makefile2:5883: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
[ 29%] Building CXX object libraries/chainbase/test/CMakeFiles/chainbase_test.dir/test.cpp.o
[ 29%] Linking CXX executable chainbase_test
[ 29%] Built target chainbase_test
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

    >>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by learnforpractice** [comment]
1. update cmake to 3.10.20171129 or above
2. git submodule update --init --recursive
3. export JAVA_HOME=
4.rename /usr/local/lib/libsecp256k1.a to other name
Sorry for the inconvenience, I'm developing on mac os x, so don't hesitate to report to me if you have encountered more build problems.

**Comment by dlwogus5038** [comment]
1. I'm using cmake 3.10.2

3. After "java --version", it return "openjdk 10.0.2 2018-07-17". Should i set 'JAVA_HOME'??

**Comment by dlwogus5038** [comment]
Before "git submodule update --init --recursive", should i delete 'externals' folder??

**Comment by dlwogus5038** [comment]
I still have these error...

[ 28%] Built target hera-buildinfo-git
[ 28%] Generating VMMain.class
[ 28%] Built target chainbase
[ 28%] Built target eosio_prods_static
Scanning dependencies of target fc
fatal: No names found, cannot describe anything.
CMake Error at version.cmake:11 (message):
  git describe failed


libraries/appbase/CMakeFiles/appbase_version.dir/build.make:57: recipe for target 'libraries/appbase/CMakeFiles/appbase_version' failed
make[2]: *** [libraries/appbase/CMakeFiles/appbase_version] Error 1
CMakeFiles/Makefile2:5525: recipe for target 'libraries/appbase/CMakeFiles/appbase_version.dir/all' failed
make[1]: *** [libraries/appbase/CMakeFiles/appbase_version.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
[ 28%] Built target aleth-buildinfo-git
[ 28%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/elliptic_impl_priv.cpp.o
[ 28%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/elliptic_secp256k1.cpp.o
3 warnings
Fatal Error: Unable to find package java.lang in classpath or bootclasspath
libraries/vm/vm_java/CMakeFiles/vm_java.dir/build.make:70: recipe for target 'libraries/vm/vm_java/VMMain.class' failed
make[2]: *** [libraries/vm/vm_java/VMMain.class] Error 3
CMakeFiles/Makefile2:4200: recipe for target 'libraries/vm/vm_java/CMakeFiles/vm_java.dir/all' failed
make[1]: *** [libraries/vm/vm_java/CMakeFiles/vm_java.dir/all] Error 2
[ 29%] Linking CXX shared library libfc.so
[ 31%] Built target fc
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

    >>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by dlwogus5038** [comment]
[ 28%] Generating VMMain.class
[ 28%] Built target eosio_prods_static
fatal: No names found, cannot describe anything.
CMake Error at version.cmake:11 (message):
  git describe failed


libraries/appbase/CMakeFiles/appbase_version.dir/build.make:57: recipe for target 'libraries/appbase/CMakeFiles/appbase_version' failed
make[2]: *** [libraries/appbase/CMakeFiles/appbase_version] Error 1
CMakeFiles/Makefile2:5525: recipe for target 'libraries/appbase/CMakeFiles/appbase_version.dir/all' failed
make[1]: *** [libraries/appbase/CMakeFiles/appbase_version.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target fc
[ 28%] Built target aleth-buildinfo-git
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
Fatal Error: Unable to find package java.lang in classpath or bootclasspath
[ 28%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/elliptic_impl_priv.cpp.o
[ 28%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/elliptic_secp256k1.cpp.o
libraries/vm/vm_java/CMakeFiles/vm_java.dir/build.make:70: recipe for target 'libraries/vm/vm_java/VMMain.class' failed
make[2]: *** [libraries/vm/vm_java/VMMain.class] Error 3
CMakeFiles/Makefile2:4200: recipe for target 'libraries/vm/vm_java/CMakeFiles/vm_java.dir/all' failed
make[1]: *** [libraries/vm/vm_java/CMakeFiles/vm_java.dir/all] Error 2
[ 29%] Linking CXX shared library libfc.so
[ 31%] Built target fc
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

    >>>>>>>>>>>>>>>>>>>> MAKE building EOSIO has exited with the above error.

**Comment by learnforpractice** [comment]
Something went wrong in getting version info in appbase CMakeLists.txt
Since I can't replicate these error on my laptop, you can try the following steps:
```
1. export JAVA_HOME= or upgrade jdk to at least version 10 and point JAVA_HOME to jdk 10, I suggest you just use "export JAVA_HOME="
2. update git to version 2.15.2 or above, as this is the git version I'm using.
3. rm -rf build;./eosio_build.sh to rebuild pyeos
4. clone pyeos to a new directory and rebuild
```
Thanks for the report and good luck.
