### ISSUE TITLE
Can I deploy a machine learning program as a smart contract ?

### ISSUE THREAD

**Issue by sivachaitanya** [learnforpractice/pyeos#69]
Can I use this library to deploy my supervised/unsupervised machine learning code wirtten in python onto the EOS network ? Can you please share your thoughts around this ?

**Comment by sivachaitanya** [comment]
awesome, what if we run the code on a private EOS network where we can issue as many tokens as we want and make sure RAM and computation requirements are met ?

**Comment by learnforpractice** [comment]
Yes, you may run your machine learning code on a private Eos network as I already did it before.

There is an out of date AI training code at the following path:

programs/pyeos/tests/python/mnist/mnist.py

But it can still give you some concept of machine learning code running directly on chain looks like.

**Comment by sivachaitanya** [comment]
awesome, I am currently working on a solution to combine machine learning code and blockchain into one platform, although running it offchain is always a fallback, after looking at pyeos, it gives me good signs that this can be possible considering EOS will go multi threaded in future release. Thanks !

**Comment by learnforpractice** [comment]
Yes, everything is possible! Just keep thinking & trying
