### ISSUE TITLE
 git submodule

### ISSUE THREAD

**Issue by CCColby** [learnforpractice/pyeos#70]
Unable to fetch in submodule path 'libraries/fc'

**Comment by shankj** [comment]
same issue

**Comment by learnforpractice** [comment]
I fixed it a few days ago and it shows no complaint when I run the following command:

git submodule  update —init —recursive



Cloning into '/home/root1/dev/pyeos2/libraries/appbase'...
Cloning into '/home/root1/dev/pyeos2/libraries/chainbase'...
Cloning into '/home/root1/dev/pyeos2/libraries/fc'...
Cloning into '/home/root1/dev/pyeos2/libraries/softfloat'...
Cloning into '/home/root1/dev/pyeos2/libraries/vm/vm_py'…

**Comment by tlkahn** [comment]
If helpful, please close. Thanks.
